# .github/workflows/build.yml

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo b -v --manifest-path ./paste_rs_api/Cargo.toml
#     - name: Run tests
#       run: cargo test --verbose
